export enum Routes {
  Landing = '/',
  Onboarding = '/onboarding',
  Login = '/login',
  ForgotPassword = '/forgot-password',
  SignUp = '/sign-up',
  Profile = '/profile',
  MyObjects = '/my-objects',
  AvailableObjects = '/dashboard',
  Builder = '/facility/:id',
  Notifications = '/notifications',
  Chat = '/messages/:id',
  Inbox = '/inbox',
  NotFound = '*',
}
